name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cc: [gcc, clang]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        deps: [sudo apt-get install, brew install, chocolatey install]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: ${{ matrix.deps }} meson
    - name: setup
      run: |
        meson setup builddir
        meson compile -C builddir# This is a basic workflow to help you get started with Actions
