name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cc: [gcc, clang]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive

    - name: dependencies (linux)
      if: ${{ matrix.os  == 'ubuntu-latest' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install meson
    - name: dependencies (macos)
      if: ${{ matrix.os  == 'macos-latest' }}
      run: brew install meson
    - name: dependencies (windows)
      if: ${{ matrix.os  == 'windows-latest' }}
      run: chocolatey install meson

    - name: build
      run: |
        meson setup builddir
        ninja -C builddir
